spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
          - id: changgou_goods_route
            uri: lb://goods
            predicates:
              - Path=/api/brand**
            filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"  # 以IP地址限流
                redis-rate-limiter.replenishRate: 1  #  填充令牌的速率
                redis-rate-limiter.burstCapacity: 1  # 令牌的容量
        #用户微服务
          - id: changgou_user_route
            uri: lb://user
            predicates:
              - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
            filters:
              - StripPrefix=1
          - id: changgou_order_route
            uri: lb://order
            predicates:
              - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
            filters:
              - StripPrefix=1
  application:
    name: gateway-web
  redis:
    host: 192.168.3.102
    port: 6379
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
  fetch-registry: false
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
